### ISSUE TITLE
Missing Quest The Spectral Chalice

### ISSUE THREAD

**Issue by pekacmarko** [Athissa/Tracker#58]
Missing Quest The Spectral Chalice
Quest for Dark Iron Bar
http://www.wowhead.com/quest=4083/the-spectral-chalice#comments

**Comment by AGrygor** [comment]
Please respect the format in the future. Thank You

**Comment by Athissa** [comment]
fixed

**Comment by pekacmarko** [comment]
quest is not fixed. 
https://www.youtube.com/watch?v=xfTEWDcwX6M
